### ISSUE TITLE
Publish latest changes to NPM

### ISSUE THREAD

**Issue by diondiondion** [souporserious/use-item-list#1]
Hi Travis,

thanks for making this library, it's a real lifesaver for me right now. However I noticed (after some struggles trying to recreate the examples) that the NPM release of the library is out of date with the changes in the repo (and the examples/documentation). If it's not too much of a hassle (and the current state of code is stable enough) it would be great if you could publish it to NPM for ease of use.

Thanks a lot!
Dion

**Comment by souporserious** [comment]
Ah, apologies for that! I meant to publish the changes and got caught up in other things. I will work on getting those published and documented properly this week!

**Comment by diondiondion** [comment]
> Ah, apologies for that! I meant to publish the changes and got caught up in other things. I will work on getting those published and documented properly this week!

Thanks a lot! I'm still super happy I stumbled across this library, it has so much potential and is a real game changer when building dropdown/menu-like components, due to the way it enables component composition, unlike solutions like dropshift where you pretty much have to give up control over the rendering of individual items.

**Comment by diondiondion** [comment]
Hi @souporserious, any update on this? Don't want to be pushy, just a reminder as I'm about to start working on another component that I'd like to use use-item-list for, where the updated API would help keep things simple :)

**Comment by souporserious** [comment]
Apologies, other projects have been taking priority over this one. However, working on this again and will have things updated soon! I appreciate your patience.

**Comment by souporserious** [comment]
Latest published under 0.1.0 🎉
