### ISSUE TITLE
FR: Support disabled items

### ISSUE THREAD

**Issue by diondiondion** [souporserious/use-item-list#2]
It would be great if use-item-list supported disabled items. This could be implemented as an additional property in the object passed to `useItem`, e.g.:

```js
const item = useItem({
  ref,
  text,
  value,
  isDisabled,
})
```

Items marked as disabled in this way should be skipped over by the `moveHighlightedItem` and `highlightItemByString` functions (even though it might be good if this was optional, as sometimes it can be beneficial for accessibility to be able to highlight disabled items).

**Comment by souporserious** [comment]
Yes, this should definitely be added! Thanks for filing an issue, I'll get started on a PR 🙂
