### ISSUE TITLE
Bug: Can't read property 'disabled' of undefined in moveHighlightedItem 

### ISSUE THREAD

**Issue by diondiondion** [souporserious/use-item-list#6]
Hi, there's a bug in `moveHighlightedItem` where `item` can be `undefined` which causes an error when the `disabled` property is accessed. I'm not sure what's causing `nextIndex` to be an invalid index. I haven't disabled the `contain` option. 

https://github.com/souporserious/use-item-list/blob/5afa6665bcdadc92e505084f5fe2b4ab4d245ca6/packages/use-item-list/src/index.ts#L169-L172

Here's a screenshot of the error message, but it's fairly obvious:
![image](https://user-images.githubusercontent.com/5636050/93785126-0329fd00-fc2e-11ea-8ec0-a9cd0f7df5b8.png)

**Comment by souporserious** [comment]
Oops, sorry about that! Hopefully, a quick fix can be just checking its existence. I really need to add tests around everything 😅

**Comment by diondiondion** [comment]
> Oops, sorry about that! Hopefully, a quick fix can be just checking its existence.

No worries! Checking for the existence of `item` would prevent the error, but shouldn't it always exist at that point, at least if `contain` isn't disabled?
