### ISSUE TITLE
FR: Initialise 'initialHighlightedIndex' with index of initially selected item

### ISSUE THREAD

**Issue by diondiondion** [souporserious/use-item-list#7]
Hi, it's me again ;)

It would be nice if `initialHighlightedIndex` was set to the index of the initially selected item if there is one, unless otherwise specified.

I had trouble getting the highlight to initialise on the selected item in my Select component, so I worked around it by using an effect that calls `useItem.highlight` when it's selected. That works, but it'd be nice if this behaviour was built-in as it seems to me like a sane default for listboxes.

```js
useEffect(() => {
  if (selected) {
    highlight();
  }
}, [selected]); // eslint-disable-line react-hooks/exhaustive-deps
```

**Comment by souporserious** [comment]
I looked into adding this to the defaults, but I think for now I like the idea of the consumer doing it like you've shown.
